name: Jet Chung

description: Snippets of the math I'm working on

avatar: https://lh3.googleusercontent.com/ogw/ADGmqu-ZIqC9NmYDit4Qt8uvJRKitrrY4TTbLR6ad6y1FQ=s192-c-mo

footer-links:
  dribbble:
  email: jetchung1@gmail.com
  facebook: 
  flickr:
  github: JetChung
  instagram: https://www.instagram.com/jetchung1/
  linkedin: https://www.linkedin.com/in/jet-chung-52793816a/
  pinterest:
  rss: 
  twitter: 
  stackoverflow:
  youtube: 
  googleplus:

url: http://jetchung.github.io/

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
