title: Snippets
email: jetchung1@gmail.com
description: >-
  Snippets of the math I'm working on or other random stuff I want to post.
baseurl: ""
url: "https://jetchung.github.io/"
github_username:  JetChung
theme: minima
plugins:
  - jekyll-feed
